In [16]:
import numpy as np
import os

In [17]:
os.getcwd()

'/home/ryan/Documents/CSC478'

In [18]:
os.chdir("/home/ryan/Documents/CSC478/Lecture2/")

In [19]:
datafile = open("populations.txt", "r")

labels_line = datafile.readline().strip()
poptable = []

total = 0

for line in datafile.readlines():
    line = line.strip()
    row = line.split("\t")
    record = [int(row[0]), float(row[1]), float(row[2]), float(row[3])]
    print record
    poptable.append(record)
    total += 1
    
print total

[1900, 30000.0, 4000.0, 48300.0]
[1901, 47200.0, 6100.0, 48200.0]
[1902, 70200.0, 9800.0, 41500.0]
[1903, 77400.0, 35200.0, 38200.0]
[1904, 36300.0, 59400.0, 40600.0]
[1905, 20600.0, 41700.0, 39800.0]
[1906, 18100.0, 19000.0, 38600.0]
[1907, 21400.0, 13000.0, 42300.0]
[1908, 22000.0, 8300.0, 44500.0]
[1909, 25400.0, 9100.0, 42100.0]
[1910, 27100.0, 7400.0, 46000.0]
[1911, 40300.0, 8000.0, 46800.0]
[1912, 57000.0, 12300.0, 43800.0]
[1913, 76600.0, 19500.0, 40900.0]
[1914, 52300.0, 45700.0, 39400.0]
[1915, 19500.0, 51100.0, 39000.0]
[1916, 11200.0, 29700.0, 36700.0]
[1917, 7600.0, 15800.0, 41800.0]
[1918, 14600.0, 9700.0, 43300.0]
[1919, 16200.0, 10100.0, 41300.0]
[1920, 24700.0, 8600.0, 47300.0]
21


In [20]:
poptable

[[1900, 30000.0, 4000.0, 48300.0],
 [1901, 47200.0, 6100.0, 48200.0],
 [1902, 70200.0, 9800.0, 41500.0],
 [1903, 77400.0, 35200.0, 38200.0],
 [1904, 36300.0, 59400.0, 40600.0],
 [1905, 20600.0, 41700.0, 39800.0],
 [1906, 18100.0, 19000.0, 38600.0],
 [1907, 21400.0, 13000.0, 42300.0],
 [1908, 22000.0, 8300.0, 44500.0],
 [1909, 25400.0, 9100.0, 42100.0],
 [1910, 27100.0, 7400.0, 46000.0],
 [1911, 40300.0, 8000.0, 46800.0],
 [1912, 57000.0, 12300.0, 43800.0],
 [1913, 76600.0, 19500.0, 40900.0],
 [1914, 52300.0, 45700.0, 39400.0],
 [1915, 19500.0, 51100.0, 39000.0],
 [1916, 11200.0, 29700.0, 36700.0],
 [1917, 7600.0, 15800.0, 41800.0],
 [1918, 14600.0, 9700.0, 43300.0],
 [1919, 16200.0, 10100.0, 41300.0],
 [1920, 24700.0, 8600.0, 47300.0]]

In [21]:
#printing the top 5 elements of poptable from index 0 up to index 5
poptable[0:5]

[[1900, 30000.0, 4000.0, 48300.0],
 [1901, 47200.0, 6100.0, 48200.0],
 [1902, 70200.0, 9800.0, 41500.0],
 [1903, 77400.0, 35200.0, 38200.0],
 [1904, 36300.0, 59400.0, 40600.0]]

In [22]:
hares = {}
lynxes = {}
carrots = {}

for row in poptable:
    hares[row[0]] = row[1]
    lynxes[row[0]] = row[2]
    carrots[row[0]] = row[3]

In [23]:
hares

{1900: 30000.0,
 1901: 47200.0,
 1902: 70200.0,
 1903: 77400.0,
 1904: 36300.0,
 1905: 20600.0,
 1906: 18100.0,
 1907: 21400.0,
 1908: 22000.0,
 1909: 25400.0,
 1910: 27100.0,
 1911: 40300.0,
 1912: 57000.0,
 1913: 76600.0,
 1914: 52300.0,
 1915: 19500.0,
 1916: 11200.0,
 1917: 7600.0,
 1918: 14600.0,
 1919: 16200.0,
 1920: 24700.0}

In [24]:
hares.keys()

[1920,
 1900,
 1901,
 1902,
 1903,
 1904,
 1905,
 1906,
 1907,
 1908,
 1909,
 1910,
 1911,
 1912,
 1913,
 1914,
 1915,
 1916,
 1917,
 1918,
 1919]

In [25]:
hares.values()

[24700.0,
 30000.0,
 47200.0,
 70200.0,
 77400.0,
 36300.0,
 20600.0,
 18100.0,
 21400.0,
 22000.0,
 25400.0,
 27100.0,
 40300.0,
 57000.0,
 76600.0,
 52300.0,
 19500.0,
 11200.0,
 7600.0,
 14600.0,
 16200.0]

In [26]:
hares.items()

[(1920, 24700.0),
 (1900, 30000.0),
 (1901, 47200.0),
 (1902, 70200.0),
 (1903, 77400.0),
 (1904, 36300.0),
 (1905, 20600.0),
 (1906, 18100.0),
 (1907, 21400.0),
 (1908, 22000.0),
 (1909, 25400.0),
 (1910, 27100.0),
 (1911, 40300.0),
 (1912, 57000.0),
 (1913, 76600.0),
 (1914, 52300.0),
 (1915, 19500.0),
 (1916, 11200.0),
 (1917, 7600.0),
 (1918, 14600.0),
 (1919, 16200.0)]

In [27]:
hares_above_50k = [yr for yr in hares.keys() if hares[yr] > 50000.0]

In [28]:
hares_above_50k

[1902, 1903, 1912, 1913, 1914]

In [29]:
maxhares = [yr for yr in hares.keys() if hares[yr] == max(hares.values())]
for i in range(0, len(maxhares)):
    print maxhares[i], hares[maxhares[i]]

1903 77400.0


In [30]:
pop = np.array(poptable)
pop

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])

In [31]:
poptable = np.loadtxt("populations.txt", skiprows=1)
poptable

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])

In [32]:
poptable.shape

(21, 4)

In [33]:
poptable.T

array([[  1900.,   1901.,   1902.,   1903.,   1904.,   1905.,   1906.,
          1907.,   1908.,   1909.,   1910.,   1911.,   1912.,   1913.,
          1914.,   1915.,   1916.,   1917.,   1918.,   1919.,   1920.],
       [ 30000.,  47200.,  70200.,  77400.,  36300.,  20600.,  18100.,
         21400.,  22000.,  25400.,  27100.,  40300.,  57000.,  76600.,
         52300.,  19500.,  11200.,   7600.,  14600.,  16200.,  24700.],
       [  4000.,   6100.,   9800.,  35200.,  59400.,  41700.,  19000.,
         13000.,   8300.,   9100.,   7400.,   8000.,  12300.,  19500.,
         45700.,  51100.,  29700.,  15800.,   9700.,  10100.,   8600.],
       [ 48300.,  48200.,  41500.,  38200.,  40600.,  39800.,  38600.,
         42300.,  44500.,  42100.,  46000.,  46800.,  43800.,  40900.,
         39400.,  39000.,  36700.,  41800.,  43300.,  41300.,  47300.]])