In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import os

In [3]:
#GET CURRENT WORKING DIR
os.getcwd()

'/home/ryan/Documents/CSC478/hw2'

In [6]:
vs = np.genfromtxt("video_store_2.csv", delimiter=",", names=True, dtype=(int, "|S1", float, int, int, float, "|S10", "|S3"))
vs

array([(1, 'M', 45000.0, 25, 32, 2.5, 'Action', 'Yes'),
       (2, 'F', 54000.0, 33, 12, 3.4, 'Drama', 'No'),
       (3, 'F', 32000.0, 20, 42, 1.6, 'Comedy', 'No'),
       (4, 'F', 59000.0, 70, 16, 4.2, 'Drama', 'Yes'),
       (5, 'M', 37000.0, 35, 25, 3.2, 'Action', 'Yes'),
       (6, 'M', 18000.0, 20, 29, 1.7, 'Action', 'No'),
       (7, 'F', 29000.0, 45, 19, 3.8, 'Drama', 'No'),
       (8, 'M', 74000.0, 25, 31, 2.4, 'Action', 'Yes'),
       (9, 'M', 38000.0, 21, 18, 2.1, 'Comedy', 'No'),
       (10, 'F', 65000.0, 40, 21, 3.3, 'Drama', 'No'),
       (11, 'F', 41000.0, 22, 48, 2.3, 'Drama', 'Yes'),
       (12, 'F', 26000.0, 22, 32, 2.9, 'Action', 'Yes'),
       (13, 'M', 83000.0, 46, 14, 3.6, 'Comedy', 'No'),
       (14, 'M', 45000.0, 36, 24, 2.7, 'Drama', 'No'),
       (15, 'M', 68000.0, 30, 36, 2.7, 'Comedy', 'Yes'),
       (16, 'M', 17000.0, 19, 26, 2.2, 'Action', 'Yes'),
       (17, 'M', 36000.0, 35, 28, 3.5, 'Drama', 'Yes'),
       (18, 'F', 6000.0, 16, 39, 1.8, 'Action', 'Yes'),

In [8]:
vs_records = vs[['Gender', 'Income', 'Age', 'Rentals', 'Avg_Per_Visit', 'Genre']]
vs_records

array([('M', 45000.0, 25, 32, 2.5, 'Action'),
       ('F', 54000.0, 33, 12, 3.4, 'Drama'),
       ('F', 32000.0, 20, 42, 1.6, 'Comedy'),
       ('F', 59000.0, 70, 16, 4.2, 'Drama'),
       ('M', 37000.0, 35, 25, 3.2, 'Action'),
       ('M', 18000.0, 20, 29, 1.7, 'Action'),
       ('F', 29000.0, 45, 19, 3.8, 'Drama'),
       ('M', 74000.0, 25, 31, 2.4, 'Action'),
       ('M', 38000.0, 21, 18, 2.1, 'Comedy'),
       ('F', 65000.0, 40, 21, 3.3, 'Drama'),
       ('F', 41000.0, 22, 48, 2.3, 'Drama'),
       ('F', 26000.0, 22, 32, 2.9, 'Action'),
       ('M', 83000.0, 46, 14, 3.6, 'Comedy'),
       ('M', 45000.0, 36, 24, 2.7, 'Drama'),
       ('M', 68000.0, 30, 36, 2.7, 'Comedy'),
       ('M', 17000.0, 19, 26, 2.2, 'Action'),
       ('M', 36000.0, 35, 28, 3.5, 'Drama'),
       ('F', 6000.0, 16, 39, 1.8, 'Action'),
       ('F', 24000.0, 25, 41, 3.1, 'Comedy'),
       ('M', 12000.0, 16, 23, 2.2, 'Action'),
       ('F', 47000.0, 52, 11, 3.1, 'Drama'),
       ('M', 25000.0, 33, 16, 2.9, 'Drama')

In [9]:
vs_names = vs_records.dtype.names
vs_names

('Gender', 'Income', 'Age', 'Rentals', 'Avg_Per_Visit', 'Genre')

In [10]:
vs_target = vs["Incidentals"]
vs_target

array(['Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No',
       'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes',
       'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'No',
       'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'], 
      dtype='|S3')

In [12]:
vs_dict = [dict(zip(vs_names, record)) for record in vs_records]
vs_dict[:5]

[{'Age': 25,
  'Avg_Per_Visit': 2.5,
  'Gender': 'M',
  'Genre': 'Action',
  'Income': 45000.0,
  'Rentals': 32},
 {'Age': 33,
  'Avg_Per_Visit': 3.3999999999999999,
  'Gender': 'F',
  'Genre': 'Drama',
  'Income': 54000.0,
  'Rentals': 12},
 {'Age': 20,
  'Avg_Per_Visit': 1.6000000000000001,
  'Gender': 'F',
  'Genre': 'Comedy',
  'Income': 32000.0,
  'Rentals': 42},
 {'Age': 70,
  'Avg_Per_Visit': 4.2000000000000002,
  'Gender': 'F',
  'Genre': 'Drama',
  'Income': 59000.0,
  'Rentals': 16},
 {'Age': 35,
  'Avg_Per_Visit': 3.2000000000000002,
  'Gender': 'M',
  'Genre': 'Action',
  'Income': 37000.0,
  'Rentals': 25}]

In [13]:
from sklearn.feature_extraction import DictVectorizer

In [14]:
vs_vec = DictVectorizer()
vs_matrix = vs_vec.fit_transform(vs_dict).toarray()

In [16]:
vs_vec.get_feature_names()

['Age',
 'Avg_Per_Visit',
 'Gender=F',
 'Gender=M',
 'Genre=Action',
 'Genre=Comedy',
 'Genre=Drama',
 'Income',
 'Rentals']

In [20]:
tpercent = 0.8
tsize = tpercent *len(vs_matrix)
vs_train = vs_matrix[:tsize, :]
vs_test = vs_matrix[tsize:, :]

/home/ryan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:3: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  app.launch_new_instance()
/home/ryan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:4: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [21]:
from sklearn import preprocessing

In [22]:
min_max_scaler = preprocessing.MinMaxScaler()

In [23]:
vs_train_norm = min_max_scaler.fit_transform(vs_train)
vs_test_norm = min_max_scaler.fit_transform(vs_test)

In [24]:
vs_train_norm[0]

array([ 0.18181818,  0.38235294,  0.        ,  1.        ,  1.        ,
        0.        ,  0.        ,  0.5       ,  0.56756757])

In [27]:
vs_target_train = vs_target[:tsize]
vs_target_test = vs_target[tsize:]
vs_target_test

/home/ryan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  if __name__ == '__main__':
/home/ryan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:2: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  from ipykernel import kernelapp as app


array(['No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No'], 
      dtype='|S3')

In [34]:
def knn_search(x, D, K, measure):
    """ FIND K NEAREST NEIGBORS OF DATA MONG K"""
    if measure == 0:
        #EUCLIDEAN DISTANCES FROM OTHER POINTS
        dists = sqrt(((D-x)**2).sum(axis=0))
    elif measure ==1:
        D_norm = np.array([np.linalg.norm(D[i]) for i in range(len(D))])
        x_norm = np.linalg.norm(x)
        sims = np.dot(D,x)/ (D_norm * x_norm)
        dists = 1 - sims
    idx = np.argsort(dists)
    return idx[:K], dists

In [35]:
neigh_idx, distances = knn_search(vs_test_norm[0], vs_train_norm, 5,1)

In [41]:
D = vs_train_norm
np.array([np.linalg.norm(D[i]) for i in range(len(D))])

array([ 1.65872981,  1.699781  ,  1.68765328,  2.05699029,  1.66996339,
        1.51785344,  1.74077134,  1.77142741,  1.51477543,  1.78607701,
        1.82413848,  1.63371936,  1.92114942,  1.64738264,  1.81802889,
        1.51301217,  1.72021331,  1.61473885,  1.75244592,  1.48581528,
        1.74301162,  1.56516744,  1.5524236 ,  1.89500202,  1.46525117,
        1.81843988,  1.90772542,  1.91661551,  1.6100141 ,  1.50646148,
        1.79190716,  1.65316476,  1.58154909,  1.57909034,  2.1215396 ,
        1.6137612 ,  1.82165211,  1.67992344,  1.84099926,  1.54648696])

In [42]:
distances

array([ 0.8043673 ,  0.06676883,  0.47636037,  0.10901649,  0.80073364,
        0.89103717,  0.09246662,  0.75313174,  0.85452615,  0.04920578,
        0.13345044,  0.47628305,  0.71504173,  0.40627743,  0.74604015,
        0.89873949,  0.44078379,  0.53599812,  0.4877924 ,  0.92840363,
        0.05178285,  0.45293945,  0.54436441,  0.08233586,  0.96147719,
        0.41120933,  0.07420151,  0.7342359 ,  0.50664818,  0.84058139,
        0.39766472,  0.4256452 ,  0.85805686,  0.44439223,  0.74855313,
        0.46699893,  0.70983791,  0.42375076,  0.42036374,  0.89154978])